const constants = {
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  SELECT_CITY_REQUEST: 'SELECT_CITY_REQUEST',
  SELECT_CITY_SUCCESS: 'SELECT_CITY_SUCCESS',
  SELECT_CITY_FAILURE: 'SELECT_CITY_FAILURE',
  SELECT_GRADE: 'SELECT_GRADE',
  SELECT_AREA: 'SELECT_AREA',
  UNSELECT_AREA: 'UNSELECT_AREA',
  SELECT_RING_GRADE: 'SELECT_RING_GRADE',
  TOGGLE_CONTACT_US: 'TOGGLE_CONTACT_US',
  TOGGLE_CITY_STATS: 'TOGGLE_CITY_STATS',
  TOGGLE_HOLC_MAPS: 'TOGGLE_HOLC_MAPS',
  TOGGLE_INTRO_MODAL: 'TOGGLE_INTRO_MODAL',
  SHOW_VISIBLE_CITIES: 'SHOW_VISIBLE_CITIES',
  MOVE_MAP: 'MOVE_MAP',
  WINDOW_RESIZED: 'WINDOW_RESIZED',
  LOADING_POLYGONS: 'LOADING_POLYGONS',
  LOADED_POLYGONS: 'LOADED_POLYGONS',
};

export default constants;
