const notInMI = [
  ['Connecticut', 'Hartford'],
  ['Connecticut', 'New London'],
  ['Indiana', 'Mushanka'],
  ['Indiana', 'Peoria'],
  ['Indiana', 'Rockford'],
  ['Indiana', 'Springfield'],
  ['Iowa', 'Cedar Rapids'],
  ['Maine', 'Portland'],
  ['Massachusetts', 'Fall River'],
  ['Massachusetts', 'Fitchburg'],

  ['Massachusetts', 'Lawrence'],
  ['Massachusetts',  'Lowell'],
  ['Massachusetts',  'Lynn'],
  ['Massachusetts',  'New Bedford'],
  ['Massachusetts',  'Pittsfield'],
  ['Massachusetts',  'Salem'],
  ['Nebraska', 'Springfield'],
  ['Nebraska', 'Lincoln'],
  ['Nebraska', 'Omaha'],
  ['New Jersey', 'Bayonne'],
  ['New Jersey', 'Hoboken'],
  ['New Jersey', 'Jersey City'],
  ['New Jersey', 'Kearney'],
  ['New Jersey', 'Newark'],
  ['New Jersey', 'northern New Jersey'],
  ['New Jersey', 'Passaic County'],
  ['New Jersey', 'Perth Amboy'],
  ['New Jersey', 'Union County'],
  ['New York', 'Jamestown'],
  ['New York', 'Mt. Vernon'],
  ['New York', 'New Rochelle'],
  ['New York', 'Yonkers'],
  ['Ohio', 'Cincinnati'],
  ['Pennsylvania', 'Reading'],
  ['Pennsylvania', 'Williamsport'],
  ['Texas', 'Wichita Falls'],
];

const forAlfred = notInMI.map(sc => ({
  uid: `${sc[0]}-${sc[1]}`,
  title: `${sc[0]} - ${sc[1]}`,
  autocomplete: `${sc[0]} ${sc[1]}`,
  subtitle: 'NOT in Mapping Inequality (via Hillier)',
  valid: 'no',
}));

console.log(JSON.stringify(forAlfred));
