const constants = {
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  SELECT_CITY_REQUEST: 'SELECT_CITY_REQUEST',
  SELECT_CITY_SUCCESS: 'SELECT_CITY_SUCCESS',
  SELECT_CITY_FAILURE: 'SELECT_CITY_FAILURE',
  SELECT_GRADE: 'SELECT_GRADE',
  SELECT_NEIGHBORHOOD: 'SELECT_NEIGHBORHOOD',
  SELECT_RING_GRADE: 'SELECT_RING_GRADE',
  TOGGLE_CONTACT_US: 'TOGGLE_CONTACT_US',
  TOGGLE_CITY_STATS: 'TOGGLE_CITY_STATS',
  TOGGLE_INTRO_MODAL: 'TOGGLE_INTRO_MODAL',
  SHOW_VISIBLE_CITIES: 'SHOW_VISIBLE_CITIES',
  MOVE_MAP: 'MOVE_MAP',
};

export default constants;
