import React from 'react';

const About = () => {
  // replace the date
  const objToday = new Date();
  const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  const todayString = `${months[objToday.getMonth()]} ${objToday.getDate()} ${objToday.getFullYear()}`;

  return (
    <React.Fragment>
      <h2>Linking to and Citing <cite>Mapping Inequality</cite></h2>
      <p>The URL for <cite>Mapping Inequality</cite> updates to reflect the current map view, which city or neighborhood or area description is selected, any React.Fragment that is open, etc. You can use those URLs to link to a particular view.</p>
      <p>You can also use those links for citations. We recommend the following format using the <cite>Chicago Manual of Style</cite>. Note the URL below reflects the current view.</p>
      <p>Robert K. Nelson, LaDale Winling, Richard Marciano, Nathan Connolly, et al., &ldquo;Mapping Inequality,&rdquo; <cite>American Panorama</cite>, ed. Robert K. Nelson and Edward L. Ayers, accessed {todayString}, {window.location.href}.</p>
      <h2>Acknowledgments</h2>
      <p><cite>Mapping Inequality</cite> was created through the collaboration of three teams at four universities.</p>
      <p>At the <a href='//dsl.richmond.edu'>University of Richmond's Digital Scholarship Lab</a>, <strong>Justin Madron</strong> managed the data and metadata for the project and <strong>Nathaniel Ayers</strong> co-designed the map. The DSL's student interns contributed an enormous amount of labor to georeferencing HOLC maps, creating polygons, and transcribing area descriptions. They are <strong>Lily Calaycay</strong>, <strong>Beaumont Smith</strong>, <strong>Rebecca Tribble</strong>, <strong>Erica Ott</strong>, <strong>Barbie Savani</strong>, <strong>Radha Zanza</strong>, <strong>Zach Halaschak</strong>, <strong>Gavin Hosman</strong>, <strong>Stefan St. John</strong>, <strong>Donald Edmonds</strong>, <strong>Haley Fortner</strong>, <strong>Max Hoffman</strong>, <strong>Amanda Lineberry</strong>, <strong>Emily Landon</strong>, <strong>Caitlin Greene</strong>, <strong>Ashley Flanigan</strong>, <strong>Leah Reistle</strong>, <strong>Gabriella Schneider</strong>, <strong>Nat Berry</strong>, <strong>Paige Warner</strong>, and <strong>Patrick Kliebert </strong>. <strong>Robert K. Nelson</strong> led the DSL team; he developed the application for <cite>Mapping Inequality</cite>, co-designed it, and contributed to its explanatory and interpretative text.</p>
      <p>At the University of Maryland, professor <strong>Richard Marciano</strong> from the <a href='http://dcic.umd.edu/'>Digital Curation Innovation Center (DCIC) at the College of Information Studies (\"Maryland's iSchool\")</a>, has led an <a href='http://dcicblog.umd.edu/mapping-inequality/'>extended team of students</a>. Current students include <strong>Mary Kendig</strong>, <strong>Myeong Lee</strong>, <strong>Maddie Allen</strong>, <strong>Martin Nikolas</strong>, <strong>Moreno Almirón</strong>, <strong>Jhon De La Cruz</strong>, <strong>Shaina Destine</strong>, <strong>Erin Durham</strong>, <strong>Darlene Reyes</strong>, <strong>Benjamin Sagay</strong>, and <strong>Sydney Vaile</strong>. This work builds on an earlier $250K IMLS-funded grant (LG-05-06-0158-06) called <a href='http://salt.umd.edu/T-RACES/'> T-RACES (Testbed for the Redlining Archives of California's Exclusionary Spaces)</a> with <strong>David Goldberg</strong> at UC Irvine and <strong>Chien-Yi Hou</strong> at UNC Chapel Hill, which digitized, georeferenced, vectorized, and made the neighborhood descriptions for all the cities of California searchable through an online database and mapping interface.  It also builds on a 2013 NSF/OCI Grant (0848296) called Cyberinfrastructure for Billions of Electronic Records (CI-BER), a cooperative agreement between NSF and NARA, with <strong>Cathy Davidson</strong> and <strong>Robert Calderbank</strong> at Duke.</p>
      <p>At Virginia Tech, assistant professor of history <strong>LaDale Winling</strong> led a team of graduate and undergraduate students who conducted research at the National Archives; georeferenced maps and created polygons; and transcribed area descriptions.  These included <strong>Mason Ailstock</strong>, <strong>Carmen Bolt</strong>, <strong>Victoria Fowler</strong>, <strong>Claire Gogan</strong>, <strong>Jordan Hill</strong>, <strong>Andrea Ledesma</strong>, <strong>Rachel Snyder</strong>, <strong>Sydney Vaile</strong>, and <strong>Rebecca Williams</strong>, along with students in two classes.  Winling is an urban and digital historian and his forthcoming book, <cite>Building the Ivory Tower</cite>, will be published by the University of Pennsylvania Press.</p>
      <p><strong>N. D. B. Connolly</strong>, the Herbert Baxter Adams Associate Professor of History at the Johns Hopkins University and the author of <cite>A World More Concrete: Real Estate and the Remaking of Jim Crow South Florida</cite>, contributed his expertise in the history of race and urban America to the conceptualization and development of <cite>Mapping Inequality</cite>, particularly its React.Fragmentual elements.</p>
      <p>We would like to thank a number of individuals and groups. <strong>Bobby Allen</strong>, <strong>Pam Lach</strong>, and <strong>Claire Clements</strong> with Nelson and Marciano inventoried the HOLC files at the National Archives at College Park. Special thanks to <strong>Cathy Davidson</strong>, distinguished professor and director of the Futures Initiative and HASTAC@CUNY, for her team's support of T-RACES at Duke University with HASTAC Director of Social Networking, <strong>Sheryl Grant</strong>, which led to the expansion of the project to the cities of North Carolina and use in a Bass Connections \"Information, Society, and Culture\" interdisciplinary research theme with <strong>Robert Calderbank</strong> at Duke University and <strong>Molly Tamarkin</strong> (now Library Director at KAUST in Saudi Arabia), with the participation of Asheville community leader <strong>Priscilla Ndiaye</strong>, and students <strong>Rachel Anderson</strong>, <strong>Felicia Arriaga</strong>, <strong>Yue Dai</strong>, and <strong>Lalita Maraj</strong>. Great appreciation to <strong>Keith Pezzoli</strong>, director of the Urban Studies and Planning Program at UC San Diego, for years of early encouragement and championing of T-RACES through the USP program from 2000 to 2006.  That redlining work was first developed with <strong>Rosemarie McKeon</strong> and presented at the ESRI User Conference in San Diego in 1999 through a poster exhibit called \"The Balkanization of Urban San Diego\" and subsequently in 2000 as a touring art exhibit led by <strong>Rosemarie McKeon,</strong> called \"Tolerance Zones\",  with <strong>Carrol Waymon</strong>, <strong>Poyin Tse</strong>, and <strong>Midi Cox</strong>. Thanks as well to <strong>John Moeser</strong> who inspired <a href='http://dsl.richmond.edu/holc/'>\"Redlining Richmond,\"</a> an important antecedent to <cite>Mapping Inequality</cite>. Finally, <a href='//stamen.com/'>Stamen Design</a> developed the <a href='//github.com/americanpanorama/panorama'>Panorama toolkit</a>, components of which are used in <strong>Mapping Inequality</strong>. </p>
      <p>The <a href='//mellon.org'>Andrew W. Mellon Foundation</a> provided the DSL generous funding to work on this and the other initial maps of <cite><a href='//dsl.richmond.edu/panorama'>American Panorama</a></cite>. The Virginia Tech College of Liberal Arts and Human Sciences also provided some funding for site development.</p>
      <div>
        <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>
          <img alt='Creative Commons License' src='https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png' />
        </a>
        <br />
        <p>This work and its data are licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a></p>.
      </div>
    </React.Fragment>
  );
}

export default About;
